### PR TITLE
Drop support for Python 3.4.

### PR DESCRIPTION
**Pull request by jugmac00**
Bumped to new major version as Python 3.4 is still the default Python interpreter for some Linux distributions.

modified:   .travis.yml
modified:   CHANGES.rst
modified:   setup.py
modified:   tox.ini

### CODE REVIEW

**Review by mgedmin — APPROVED** [review]

**Comment by icemac** [comment]
This package does not contain a single line of code (besides the namespace package boiler plate). Should we remove the TravisCI integration and the test setup configuration?

**Comment by jugmac00** [comment]
There are some hits if you search for the package name on github:

Looks like even plone/volto depends on "Products.OFSP" 

I am still not sure where to draw the line "keep package so others can still depend on it" and "shut it down as it contains no code".

**Comment by mgedmin** [comment]
> I am still not sure where to draw the line "keep package so others can still depend on it" and "shut it down as it contains no code".

I understood the suggestion as "keep the package but drop explicit Python version classifiers and Travis setup".

**Comment by jugmac00** [comment]
Well, when we drop TravisCI, it theoretically could break with a future Python version.

I'd suggest to either shut it down (archive) completely, or keep TravisCI support. But it's not on me to make a call as I cannot estimate the consequences.

**Pull request merged**
